name: Sync with staging

on:
    push:
        branches: [development]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            SSH_USERNAME: ${{ secrets.PAGELY_SSH_USER }}
            SSH_KEY: ${{ secrets.PAGELY_SSH_KEY }}
            SSH_PORT: ${{ secrets.PAGELY_SSH_PORT }}
            SSH_HOST: ${{ secrets.PAGELY_SSH_HOST }}
            SSH_PATH: ${{ secrets.SSH_STAGING_PATH }}
        steps:
            - name: Check out source files
              uses: actions/checkout@v2
            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Configure Composer cache
              uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-
            - name: Install composer deps
              run: composer install --no-dev --prefer-dist --no-progress --no-suggest
            - name: Install npm deps
              run: npm ci --legacy-peer-deps
            - name: Build files
              run: npm run build
            - name: Zip files
              run: npm run dist
            - name: Run deploy
              uses: pagely/action-deploy@v1
              with:
                PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/plugins/otter-blocks"
                PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
                PAGELY_INTEGRATION_ID: ${{secrets.PAGELY_INTEGRATION_ID}}
                PAGELY_APP_ID: ${{secrets.PAGELY_APP_ID_STAGING}}
                PAGELY_WORKING_DIR: ${{github.workspace}}/dist/otter-blocks